In [1]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
import pickle

In [2]:
with open('Dataset/train_X.p', 'rb') as f:
    train_X = pickle.load(f)
train_X.head()

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,5,0,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,1,2,0,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
with open('Dataset/train_y.p', 'rb') as f:
    train_y= pickle.load(f)
train_y.head()

0    2
1    9
2    6
3    0
4    3
Name: label, dtype: int64

In [4]:
with open('Dataset/test_X.p', 'rb') as f:
    test_X = pickle.load(f)
test_X.head()

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,9,8,0,...,103,87,56,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,14,53,99,17,...,0,0,0,0,63,53,31,0,0,0
3,0,0,0,0,0,0,0,0,0,161,...,137,126,140,0,133,224,222,56,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
with open('Dataset/test_y.p', 'rb') as f:
    test_y = pickle.load(f)
test_y.head()

0    0
1    1
2    2
3    2
4    3
Name: label, dtype: int64

In [8]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(train_X.values,train_y.values)
y_pred= knn.predict(test_X.values)
print("acc",accuracy_score(test_y.values,y_pred))

acc 0.8589

In [10]:
from sklearn.decomposition import PCA
n_components =60
pca = PCA(n_components=n_components, svd_solver='randomized',whiten=True).fit(train_X)
X_train_pca = pca.transform(train_X)
train_new=np.array(X_train_pca)
X_test_pca = pca.transform(test_X)
test_new=np.array(X_test_pca)
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(train_new,train_y.values)
y_pred= knn.predict(test_new)
print("acc",accuracy_score(test_y.values,y_pred))

acc 0.8617

In [18]:
X_train_pca = pca.transform(train_X)
train_new=np.array(X_train_pca)
X_test_pca = pca.transform(test_X)
test_new=np.array(X_test_pca)

In [7]:
kvals=range(1,15,2)
accuracy=[]
n_components = [20,40,60,80]
for k in kvals:
    for nc in n_components:
       train_new = PCA(n_components=nc, svd_solver='randomized',whiten=True).fit_transform(train_X)
       knn = KNeighborsClassifier(n_neighbors=k)
       score = cross_val_score(knn,train_new,train_y,cv=10,scoring='accuracy')
       accuracy.append(score.mean()*100)
       print(k,nc,score.mean()*100)

1 20 83.34
1 40 84.6766666667
1 60 85.2333333333
1 80 85.2633333333
3 20 84.705
3 40 85.5333333333
3 60 85.9483333333
3 80 85.9533333333
5 20 85.245
5 40 86.0066666667
5 60 86.2416666667
5 80 86.215
7 20 85.2966666667
7 40 86.0416666667
7 60 86.1583333333
7 80 86.12
9 20 85.33
9 40 86.06
9 60 86.1733333333
9 80 85.9066666667
11 20 85.34
11 40 86.0033333333
11 60 86.1166666667
11 80 85.9683333333
13 20 85.305
13 40 85.9016666667
13 60 86.0
13 80 85.6966666667

In [51]:
new_data = pd.read_csv("Dataset/myimages4.csv")

In [52]:
ntrain_X=new_data.drop('label',axis=1)
ntrain_X.head()

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,1,2,0,...,165,145,151,48,0,2,0,0,0,0
1,0,0,0,0,0,0,1,1,0,0,...,89,97,106,113,42,0,1,0,0,0
2,0,0,0,0,25,25,25,25,25,29,...,35,13,29,48,61,59,0,0,0,0
3,0,0,0,0,0,0,0,0,0,2,...,40,5,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,2,0,0,1,...,29,0,1,0,0,0,0,0,0,0

In [53]:
ntrain_y=new_data[:]['label']
ntrain_y.head()

0    0
1    0
2    0
3    0
4    0
Name: label, dtype: int64

In [54]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(train_X.values,train_y.values)
y_pred= knn.predict(ntrain_X.values)
print("acc",accuracy_score(ntrain_y.values,y_pred))

acc 0.617283950617

In [55]:
list(zip(y_pred,ntrain_y.values))

[(6, 0),
 (0, 0),
 (6, 0),
 (6, 0),
 (6, 0),
 (0, 0),
 (6, 0),
 (0, 0),
 (2, 0),
 (2, 0),
 (6, 0),
 (6, 0),
 (6, 0),
 (0, 0),
 (4, 0),
 (6, 0),
 (0, 0),
 (2, 0),
 (6, 0),
 (0, 0),
 (2, 0),
 (6, 0),
 (2, 0),
 (6, 0),
 (2, 0),
 (4, 0),
 (0, 0),
 (0, 0),
 (6, 0),
 (6, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (3, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (4, 2),
 (4, 2),
 (6, 2),
 (6, 2),
 (4, 2),
 (4, 2),
 (2, 2),
 (4, 2),
 (6, 2),
 (8, 2),
 (4, 2),
 (4, 2),
 (2, 2),
 (0, 2),
 (2, 2),
 (4, 2),
 (2, 2),
 (6, 2),
 (2, 2),
 (2, 2),
 (6, 2),
 (4, 2),
 (4, 2),
 (6, 2),
 (4, 2),
 (2, 2),
 (6, 2),
 (4, 2),
 (4, 2),
 (3, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (6, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (6, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (4, 4),
 (2, 4),
 (4, 4),
 (4, 4),
 (4, 4),
 (4, 4),
 (4, 4),
 (4, 4),
 (2, 4),
 (4, 4),
 (4, 4),
 (3, 4),
 (4, 4),
 (4, 4),
 (4, 4),
 (6, 4),
 (0, 4),
 (4, 4),
 (0, 4),
 (4, 4),
 (4, 4),
 (2, 4),
 (4, 4),
 (0, 4),
 (4, 4),
 (2, 4),
 (6, 4),
 (4, 4),
 (4, 4),
 (2, 4),
 (4, 4),
 (4, 4),
 (3, 4),
 (4, 4),
 (4, 4),
 (3, 4),
 (4, 4),
 (6, 4),
 (4, 4),
 (4, 4),
 (4, 4),
 (4, 4),
 (4, 4),
 (4, 4),
 (3, 4),
 (4, 4),
 (4, 4),
 (8, 5),
 (6, 5),
 (7, 5),
 (9, 5),
 (7, 5),
 (5, 5),
 (5, 5),
 (7, 7),
 (0, 7),
 (7, 7),
 (9, 7),
 (5, 7),
 (7, 7),
 (7, 7),
 (7, 7),
 (8, 7),
 (7, 7),
 (7, 7),
 (7, 7),
 (7, 7),
 (7, 7),
 (7, 7),
 (8, 7),
 (9, 7),
 (8, 7),
 (8, 7),
 (7, 7),
 (8, 7),
 (7, 7),
 (7, 7),
 (7, 7),
 (8, 7),
 (7, 7),
 (7, 7),
 (7, 7),
 (7, 7),
 (7, 7),
 (8, 7),
 (7, 7),
 (8, 7),
 (8, 7),
 (7, 7),
 (5, 7),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (2, 8),
 (8, 8),
 (8, 8),
 (8, 8),
 (4, 8),
 (8, 8),
 (8, 8),
 (8, 9),
 (8, 9),
 (8, 9),
 (8, 9),
 (9, 9),
 (0, 9),
 (4, 9),
 (3, 9),
 (6, 9),
 (7, 9),
 (8, 9),
 (0, 9),
 (8, 9),
 (8, 9),
 (8, 9),
 (9, 9),
 (2, 9),
 (9, 9),
 (2, 9),
 (0, 9),
 (9, 9),
 (9, 9),
 (9, 9),
 (2, 9),
 (9, 9),
 (2, 9),
 (9, 9),
 (9, 9),
 (8, 9),
 (8, 9),
 (8, 9),
 (8, 9),
 (8, 9),
 (6, 9),
 (4, 9),
 (8, 9),
 (8, 9),
 (8, 9),
 (8, 9),
 (0, 9),
 (9, 9),
 (8, 9),
 (6, 9),
 (2, 9),
 (8, 9),
 (8, 9),
 (8, 9),
 (0, 9),
 (8, 9),
 (2, 9),
 (6, 9)]

In [50]:
ntrain_y.values

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])

In [62]:
n_components =60
pca = PCA(n_components=n_components, svd_solver='randomized',whiten=True).fit(train_X)
X_train_pca = pca.transform(train_X)
train_new=np.array(X_train_pca)
X_test_pca = pca.transform(ntrain_X)
test_new=np.array(X_test_pca)
knn1 = KNeighborsClassifier(n_neighbors=3)
knn1.fit(train_new,train_y.values)
y_pred= knn1.predict(test_new)
print("acc",accuracy_score(ntrain_y.values,y_pred))

acc 0.577160493827